# application.properties의 형식

#server.port=8081
#spring.datasource.url=jdbc:mariadb://localhost:3306/member
#spring.datasource.username=root
#spring.datasource.password=1234

# application.yml의 형식

#server:
#  port: 8081
#
#spring:
#  profiles:
#    active: dev # 개발용으로 사용
#  datasource:
#    url: jdbc:mariadb://localhost:3306/member
#    username: root
#    password: 1234

#--- # 설정 구분
#server:
#  port: 8081
#
#spring:
#  profiles:
#    active: prod # 운영용으로 사용
#  datasource:
#    url: jdbc:mariadb://localhost:3306/member
#    username: root
#    password: 1234
